In [20]:
import walker
import itertools
import dgl.function as fn
import networkx as nx
import dgl
import torch

In [34]:
# Load and pre-process data
from data import get_dataset


adj, features, labels, idx_train, idx_val, idx_test = get_dataset('cora', 3)

# change the format into networkx
G = nx.Graph()
edge_index = adj._indices().numpy()
G.add_edges_from(edge_index.T)   

  NumNodes: 2708
  NumEdges: 10556
  NumFeats: 1433
  NumClasses: 7
  NumTrainingSamples: 140
  NumValidationSamples: 500
  NumTestSamples: 1000
Done loading data from cached files.


/home/jacklu/anaconda3/envs/pyg-gpu/lib/python3.8/site-packages/dgl/heterograph.py:3719: DGLWarning: DGLGraph.adjacency_matrix_scipy is deprecated. Please replace it with:

	DGLGraph.adjacency_matrix(transpose, scipy_fmt="csr").

  dgl_warning('DGLGraph.adjacency_matrix_scipy is deprecated. '


In [35]:
t_num = 5
w_len = 5

In [39]:
G = dgl.DGLGraph(G)

/home/jacklu/anaconda3/envs/pyg-gpu/lib/python3.8/site-packages/dgl/heterograph.py:72: DGLWarning: Recommend creating graphs by `dgl.graph(data)` instead of `dgl.DGLGraph(data)`.
  dgl_warning('Recommend creating graphs by `dgl.graph(data)`'


In [43]:
# nodes_features = torch.empty(G.nodes().size(dim=0), t_num*w_len)
nodes_features = [] 
# 遍历张量
for i in range(G.nodes().size(dim=0)):
    strat_nodes = [i] * t_num

    token_path = dgl.sampling.random_walk(G, strat_nodes, length=w_len)
    print(token_path[0])
    nodes_features.append(token_path[0])

tensor([[   0,  633,    0,  633, 1866,  633],
        [   0,  633,    0,  633,    0,  633],
        [   0,  633, 1866,  633, 1866, 1701],
        [   0,  633, 1701, 1479,  873,  261],
        [   0,  633, 1866, 1701, 1323, 1701]])
tensor([[   1,  652,    1,  654,    1,  654],
        [   1,    2,    1,    2,    1,  654],
        [   1,  654,    1,  652,  470,  652],
        [   1,  652,    1,  654,    1,    2],
        [   1,    2,  332,  665, 2120, 2040]])
tensor([[   2, 1666,   49, 2034,  224, 2034],
        [   2, 1454,    2,    1,    2,  332],
        [   2, 1454,    2,  332,    2, 1454],
        [   2, 1666,   48, 2205, 1952,  942],
        [   2,  332, 2122,  665, 2122, 2123]])
tensor([[   3, 2544,    3, 2544,    3, 2544],
        [   3, 2544,    3, 2544,    3, 2544],
        [   3, 2544,    3, 2544,    3, 2544],
        [   3, 2544,    3, 2544,    3, 2544],
        [   3, 2544,    3, 2544,    3, 2544]])
tensor([[   4, 1256, 2176,  595, 1256, 1091],
        [   4, 1761,  223, 115

In [45]:
torch.save(nodes_features, 'cora' + '_t_num=' + str(t_num) + '_w_len=' + str(w_len) + '.pt')

In [52]:
nodes_features[0].tolist()

[[0, 633, 0, 633, 1866, 633],
 [0, 633, 0, 633, 0, 633],
 [0, 633, 1866, 633, 1866, 1701],
 [0, 633, 1701, 1479, 873, 261],
 [0, 633, 1866, 1701, 1323, 1701]]

In [46]:
nodes_features = torch.load('cora_t_num=5_w_len=5.pt', map_location=torch.device('cpu'))
for node_features in nodes_features:
    te

[tensor([[   0,  633,    0,  633, 1866,  633],
         [   0,  633,    0,  633,    0,  633],
         [   0,  633, 1866,  633, 1866, 1701],
         [   0,  633, 1701, 1479,  873,  261],
         [   0,  633, 1866, 1701, 1323, 1701]]),
 tensor([[   1,  652,    1,  654,    1,  654],
         [   1,    2,    1,    2,    1,  654],
         [   1,  654,    1,  652,  470,  652],
         [   1,  652,    1,  654,    1,    2],
         [   1,    2,  332,  665, 2120, 2040]]),
 tensor([[   2, 1666,   49, 2034,  224, 2034],
         [   2, 1454,    2,    1,    2,  332],
         [   2, 1454,    2,  332,    2, 1454],
         [   2, 1666,   48, 2205, 1952,  942],
         [   2,  332, 2122,  665, 2122, 2123]]),
 tensor([[   3, 2544,    3, 2544,    3, 2544],
         [   3, 2544,    3, 2544,    3, 2544],
         [   3, 2544,    3, 2544,    3, 2544],
         [   3, 2544,    3, 2544,    3, 2544],
         [   3, 2544,    3, 2544,    3, 2544]]),
 tensor([[   4, 1256, 2176,  595, 1256, 1091],
     